# Generated by Django 3.1.2 on 2021-06-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210616_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='despriction',
            new_name='description',
        ),
    ]
