# Generated by Django 3.1.2 on 2021-06-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_varaiationmanager_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaraiationManager',
        ),
    ]
