# Generated by Django 3.1.2 on 2021-06-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
