# Generated by Django 3.1 on 2021-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
